name = "classroom-live"
main = "src/worker.js"
compatibility_date = "2026-08-20"

[[durable_objects.bindings]]
name = "ROOMS"
class_name = "Room"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Room"]

[[kv_namespaces]]
binding = "PDF_STORE"
id ="abb11eefc74b471a8ed1757722a50c11"
